### 7mi-TCT CONFIG ###

### コンフィグを編集したら、必ず /tctreload をしてください。

## ゲームのスタートなどができるプレイヤーを設定します。
# 例
# admin: ["Steve", "Alex"]
admin: [""]

roles:
## それぞれの役職の人数を変更します。
#
# 村人 - villagers
# 探偵 - detectives
# 人狼 - wolves
# 狂人 - fanatics
# 妖狐 - foxes
#
# 0にするとその役職は無効になります。
# また、-1にすると、人数に合わせて変動します。
# 数値1..数値2 と入力すると最小値が数値1で最大値が数値2になります。
# 数値1:数値2 と入力すると数値2が優先度になります。
# 優先度は0が最優先です。
# 最下位にする場合は何も入力しない、または-1を入力します。
#
# コマンドでは /setrolecount <役職名> <数値>
# 例1 /setrolecount detectives 2
# 例2 /setrolecount villagers 3..-1:0
# (上記のコマンドが実行できるのは、adminで設定したプレイヤーのみです)
#
# よくわからなかったら触らないでコマンドで操作した方がいいです。(その方が楽)
  count:
    villagers: 2..-1:0
    detectives: 1
    wolves: 1
    fanatics: 1..2:1
    foxes: 1
# 例
# count:
#   villagers: 2..-1:0
#   detectives: 1:-1
#   wolves: 1:-1
#   fanatics: 1..2:1
#   foxes: 1:-1
#
# 人数が6人の場合、
# 村人: 2
# 探偵: 1
# 人狼: 1
# 狂人: 1
# 妖狐: 1
#
# 人数が7人の場合、
# 村人: 2
# 探偵: 1
# 人狼: 1
# 狂人: 2
# 妖狐: 1
#
# 人数が8人の場合、
# 村人: 3
# 探偵: 1
# 人狼: 1
# 狂人: 2
# 妖狐: 1
#
# 人数が5人以下の場合、
# 開始不可
