### 7mi-TCT CONFIG ###

### コンフィグを編集したら、必ず /tctreload をしてください。

## ゲームのスタートなどができるプレイヤーを設定します。
# 例
# admin: ["Steve", "Alex"]
#
# オペレーターにadmin権限を与える場合はopと入力します。
admin: [""]

roles:
## それぞれの役職の人数を変更します。
#
# 医者 - healer
# 探偵 - detectives
# 人狼 - wolves
# 狂人 - fanatics
# 妖狐 - foxes
#
# 0にするとその役職は無効になります。
#
# コマンドでは /setrolecount <役職名> <数値>
# 例1 /setrolecount detectives 2
# (上記のコマンドが実行できるのは、adminで設定したプレイヤーのみです)
#
# よくわからなかったら触らないでコマンドで操作した方がいいです。(その方が楽)
  count:
    healers: 1
    detectives: 1
    wolves: 1
    fanatics: 1
    foxes: 1
# 例
# count:
#   healers: 1
#   detectives: 1
#   wolves: 1
#   fanatics: 1
#   foxes: 1
#
# 人数が6人の場合、
# 村人: 1
# 医者: 1
# 探偵: 1
# 人狼: 1
# 狂人: 1
# 妖狐: 1
#
# 人数が7人の場合、
# 村人: 2
# 医者: 1
# 探偵: 1
# 人狼: 1
# 狂人: 1
# 妖狐: 1
#
# 人数が8人の場合、
# 村人: 3
# 医者: 1
# 探偵: 1
# 人狼: 1
# 狂人: 1
# 妖狐: 1
#
# 人数が5人以下の場合、
# 開始不可


#ゲーム開始時に所持しているコイン枚数
#
#デフォルト
# coin:
#   villagers: 0
#   healers: 0
#   detectives: 2
#   wolves: 2
#   fanatics: 0
#   foxes: 0
  coin:
    villagers: 0
    healers: 0
    detectives: 2
    wolves: 2
    fanatics: 0
    foxes: 0

countdown:
  #デフォルト: 10秒
  prestart: 10 #準備時間 (秒)
  #デフォルト: 210秒
  game: 210 #ゲーム残り時間 (秒)
  addcount:
    #デフォルト: 8以上12以下
    kill: 20 #キルしたときに増える時間 (秒)

#デフォルト: 20秒
quickchat-cooldown: 20 #クイックチャットのクールタイム (秒)

#デフォルト: 20秒
heal-station-cooldown: 20 #回復ステーションのクールタイム (秒)

#デフォルト: 180秒後
first-coin-time: 180 #コインが配られる時間 (秒後)

player:
# プレイヤーの名前を指定した名前に置き換えることができます。
  name-replace: